spring:
  datasource:
    url: jdbc:sqlserver://testsbserver.database.windows.net:1433;database=testdb123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admin123
    password: Admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9090


